version: 2.1

executors:
  node-executor:
    docker:
      - image: cypress/browsers:node16.16.0-chrome107-ff107
    working_directory: ~/app

jobs:
  test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Cypress tests
          command: npx cypress run

workflows:
  version: 2
  test:
    jobs:
      - test