version: 2.1

orbs:
  cypress: cypress-io/cypress@3

jobs:
  cypress-run:
    docker:
      - image: cypress/browsers:node-18.12.0-chrome-107
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run Cypress tests with Mochawesome reporting
          command: npx cypress run
      - store_artifacts:
          path: cypress/videos
          destination: videos
      - store_artifacts:
          path: cypress/screenshots
          destination: screenshots
      - store_artifacts:
          path: cypress/reports/mochawesome
          destination: mochawesome-report

workflows:
  version: 2
  run-cypress-tests:
    jobs:
      - cypress-run